sudo: false
services: mongodb

notifications:
  email: false

language: ruby
before_install: gem install bundler
cache: bundler
rvm:
  - 2.1
  - 2.2
  - jruby-9.0.0.0
gemfile:
  - Gemfile
  - gemfiles/mongoid-3.1.gemfile
  - gemfiles/mongoid-4.0.gemfile
  - gemfiles/mongoid-5.0.gemfile
matrix:
  fast_finish: true
  include:
    - rvm: 2.2.2
      gemfile: gemfiles/mongoid-6.0.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/mongoid-6.0.gemfile

env:
  global:
    env:
      - RUBYOPT='-W0'
