sudo: false

services: mongodb

notifications:
  email: false

language: ruby

before_install:
  gem update bundler

cache: bundler

rvm:
  - 2.3.1

gemfile:
  - Gemfile
  - gemfiles/mongoid-3.1.gemfile
  - gemfiles/mongoid-4.0.gemfile
  - gemfiles/mongoid-5.0.gemfile
  - gemfiles/mongoid-6.0.gemfile

env:
  global:
    env:
      - RUBYOPT='-W0'
